%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\LBecce\Desktop\tmp\taser1510_1448.csv
%
% Auto-generated by MATLAB on 20-Oct-2021 15:15:43

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3", "VarName4", "VarName5", "VarName6", "Var7", "Var8", "Var9"];
opts.SelectedVariableNames = ["VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
grezzi = readtable("C:\Users\LBecce\Desktop\tmp\taser1510_1448.csv", opts);


%% Clear temporary variables
clear opts